export const destinationDetails = {
  lumbini: {
    title: 'Gorakhpur to Lumbini Taxi Service',
    description: `Lumbini Province is a province in western Nepal. The country's third largest province in terms of area as well as population, Lumbini is home to the World Heritage Site of Lumbini, where according to the Buddhist tradition, the founder of Buddhism, Gautama Buddha was born.`,
    image: '/assets/image/popularDestination/PD_Lumbini.jpg',
    places: [
      'Maya Devi Temple',
      'Bodhi Tree',
      'Ashoka Pillar',
      'Lumbini Museum',
      'China Temple',
      'Royal Thai Monastery',
      'Dae Sung Shakya',
      'Eternal Peace Flame',
      'Myanmar Golden Monastery',
      'Kapilvastu',
      'Kudan Stupa',
      'World Peace Pagoda',
      'Lumbini Development Zone',
      'Lumbini Crane Sanctuary',
    ],
    terms: [
      'If you are returning in same day then we will give you best possible discount',
      'Minimum Limit per day 250 KM',
      'Driver Allowance - Rs.250/Day',
      'Charge will be applicable garage to garage',
      'Toll and parking extra',
      'UP and Hariyana for state tax Free (Other state will be applicable)',
      'If you are choosing our service for only dropping then we will give you more discounted price',
    ]
  },
  gorakhnath: {
    title: 'Gorakhpur to Gorakhnath Temple Taxi Service',
    description: 'Ancient temple dedicated to Guru Gorakhnath, a major pilgrimage site in Gorakhpur.',
    image: '/assets/image/popularDestination/PD_Gorakhnath.jpg',
    places: [
      'Gorakhnath Temple',
      'Temple Museum',
      'Temple Gardens',
      'Nearby Markets',
    ],
    terms: [
      'Minimum Limit per day 80 KM',
      'Driver Allowance - Rs.250/Day',
      'Toll and parking extra',
      'Garage to garage charge applicable',
    ]
  },
  
  pokhara: {
    title: 'Gorakhpur to Pokhara Taxi Service',
    description: `Pokhara is a city on Phewa Lake, in central Nepal. It's known as a gateway to the Annapurna Circuit, a popular trail in the Himalayas. Tal Barahi Temple, a 2-story pagoda, sits on an island in the lake. On the eastern shore, the Lakeside district has yoga centers and restaurants. In the city's south, the International Mountain Museum has exhibits on the history of mountaineering and the people of the Himalayas.`,
    image: '/assets/image/popularDestination/PD_Pokhara.jpg',
    places: [
      'Phewa Lake',
      'Sarangkot',
      'Davis Falls',
      'World Peace Pagoda',
      'Trekking',
      'Hiking',
      'Paragliding',
      'Bungee Jumping',
    ],
    terms: [
      'If you are returning in same day then we will give you best possible discount',
      'Minimum Limit per day 250 KM',
      'Driver Allowance - Rs.250/Day',
      'Charge will be applicable garage to garage',
      'Toll and parking extra',
      'UP and Hariyana for state tax Free (Other state will be applicable)',
      'If you are choosing our service for only dropping then we will give you more discounted price',
    ]
  },
  varanasi: {
    title: 'Gorakhpur to Varanasi Taxi Service',
    description: `Varanasi is one of the largest cities of the Punjab state in India. The city lies on the main Grand Trunk Road (GT Road) from Delhi to Varanasi connecting to Lahore in Pakistan. Varanasi is a city with a splendid blend of tradition and culture. With important religious centers and historical sites, the city reveals a magnificent past and a promising future. The city is known as the Jewel of Punjab. There are several heritage and religious attractions in Varanasi.`,
    image: '/assets/image/popularDestination/PD_Varanasi.jpg',
    places: [
      'Dashashwamedh Ghat',
      'Manikarnika Ghat',
      'Kashi Vishwanath Temple',
      'Bharat Mata Mandir',
      'Durga Mandir',
      'Ganga Aarti',
      'Assi Ghat',
      'Ganga Mahotsav',
      'Ram Nagar Fort',
      'Vishwanath Gali',
    ],
    terms: [
      'If you are returning in same day then we will give you best possible discount',
      'Minimum Limit per day 250 KM',
      'Driver Allowance - Rs.250/Day',
      'Charge will be applicable garage to garage',
      'Toll and parking extra',
      'UP and Hariyana for state tax Free (Other state will be applicable)',
      'If you are choosing our service for only dropping then we will give you more discounted price',
    ]
  },
  lucknow: {
    title: 'Gorakhpur to Lucknow Taxi Service',
    description: `Lucknow, a large city in northern India, is the capital of the state of Uttar Pradesh. Toward its center is Rumi Darwaza, a Mughal gateway. Nearby, the 18th-century Bara Imambara shrine has a huge arched hall. Upstairs, Bhool Bhulaiya is a maze of narrow tunnels with city views from its upper balconies. Close by, the grand Victorian Husainabad Clock Tower was built as a victory column in 1881`,
    image: '/assets/image/popularDestination/PD_Lucknow.jpg',
    places: [
      'Bara Imambara',
      'Hazratganj',
      'Janeshwar Mishra Park',
      'Aminabad',
      'Gomti Riverfront Park',
      'Rumi Darwaza',
      'Anandi Water Park',
      'Hazratganj Market',
      'Marine Drive',
    ],
    terms: [
      'If you are returning in same day then we will give you best possible discount',
      'Minimum Limit per day 250 KM',
      'Driver Allowance - Rs.250/Day',
      'Charge will be applicable garage to garage',
      'Toll and parking extra',
      'UP and Hariyana for state tax Free (Other state will be applicable)',
      'If you are choosing our service for only dropping then we will give you more discounted price',
    ]
  },
  kathmandu: {
    title: 'Gorakhpur to Kathmandu Taxi Service',
    description: `Kathmandu, Nepal's capital, is set in a valley surrounded by the Himalayan mountains. At the heart of the old city's mazelike alleys is Durbar Square, which becomes frenetic during Indra Jatra, a religious festival featuring masked dances. Many of the city's historic sites were damaged or destroyed by a 2015 earthquake. Durbar Square's palace, Hanuman Dhoka, and Kasthamandap, a wooden Hindu temple, are being rebuilt.`,
    image: '/assets/image/popularDestination/PD_Kathmandu.jpg',
    places: [
      'Patan Darbar Square',
      'Garden of Dreams',
      'Bhaktapur Durbar Square',
      'Narayanhiti Royal Palace',
      'Hiranya Varna Mahavihar',
      'Dharahara',
      'Patan Museum',
      'National Museum of Nepal',
      'Taragaon Next',
    ],
    terms: [
      'If you are returning in same day then we will give you best possible discount',
      'Minimum Limit per day 250 KM',
      'Driver Allowance - Rs.250/Day',
      'Charge will be applicable garage to garage',
      'Toll and parking extra',
      'UP and Hariyana for state tax Free (Other state will be applicable)',
      'If you are choosing our service for only dropping then we will give you more discounted price',
    ]
  }
}; 